n_sim: 5                     # Number of replica simulations
n_iter: 1500                 # Number of iterations
s: 15                        # Shift in λ ranges [e.g. s = 2 if λ_2 = [2, 3, 4] & λ_3 = [4, 5, 6]]
nst_sim: 10000                # Number of simulation steps for each homogeneous replica
proposal: 'exhaustive'
mdp: 'expanded.mdp'
add_swappables: [[10, 15], [10, 16], [10, 17], [10, 18], [10, 19], [11, 15], [11, 16], [11, 17], [11, 18], [11, 19], [12, 15], [12, 16], [12, 17], [12, 18], [12, 19], [13, 15], [13, 16], [13, 17], [13, 18], [13, 19], [14, 15], [14, 16], [14, 17], [14, 18], [14, 19], [25, 30], [25, 31], [25, 32], [25, 33], [25, 34], [26, 30], [26, 31], [26, 32], [26, 33], [26, 34], [27, 30], [27, 31], [27, 32], [27, 33], [27, 34], [28, 30], [28, 31], [28, 32], [28, 33], [28, 34], [29, 30], [29, 31], [29, 32], [29, 33], [29, 34], [40, 45], [40, 46], [40, 47], [40, 48], [40, 49], [41, 45], [41, 46], [41, 47], [41, 48], [41, 49], [42, 45], [42, 46], [42, 47], [42, 48], [42, 49], [43, 45], [43, 46], [43, 47], [43, 48], [43, 49], [44, 45], [44, 46], [44, 47], [44, 48], [44, 49], [55, 60], [55, 61], [55, 62], [55, 63], [55, 64], [56, 60], [56, 61], [56, 62], [56, 63], [56, 64], [57, 60], [57, 61], [57, 62], [57, 63], [57, 64], [58, 60], [58, 61], [58, 62], [58, 63], [58, 64], [59, 60], [59, 61], [59, 62], [59, 63], [59, 64]]
n_ckpt: 50
N_cutoff: -1
w_combine: False
runtime_args: {'-ntomp': '4', '-ntmpi': '1'}
grompp_args: {'-maxwarn': '2'}
gro: ['A-B.gro', 'B-C.gro', 'C-D.gro', 'D-E.gro', 'E-F.gro'] 
top: ['A-B.top', 'B-C.top', 'C-D.top', 'D-E.top', 'E-F.top'] 
gmx_executable: 'gmx'
verbose: True
modify_coords: 'swap_gro'

msm: False
free_energy: True
df_spacing: 1
df_method: "MBAR"
err_method: "propagate"
n_bootstrap: 50
seed : null
