n_sim: 7                    # Number of replica simulations
n_iter: 1000                # Number of iterations
s: 9                        # Shift in λ ranges [e.g. s = 2 if λ_2 = [2, 3, 4] & λ_3 = [4, 5, 6]]
nst_sim: 10000               # Number of simulation steps for each homogeneous replica
proposal: 'exhaustive'
mdp: 'expanded.mdp'
add_swappables: [[6, 9], [6, 10], [6, 11], [7, 9], [7, 10], [7, 11], [8, 9], [8, 10], [8, 11], [15, 18], [15, 19], [15, 20], [16, 18], [16, 19], [16, 20], [17, 18], [17, 19], [17, 20], [24, 27], [24, 28], [24, 29], [25, 27], [25, 28], [25, 29], [26, 27], [26, 28], [26, 29], [33, 36], [33, 37], [33, 38], [34, 36], [34, 37], [34, 38], [35, 36], [35, 37], [35, 38], [0, 45], [1, 45], [2, 45], [0, 46], [1, 46], [2, 46], [0, 47], [1, 47], [2, 47], [24, 51], [25, 51], [26, 51], [24, 52], [25, 52], [26, 52],[24, 53], [25, 53], [26, 53], [51, 54], [52, 54], [53, 54], [51, 55], [52, 55], [53, 55], [51, 56], [52, 56], [53, 56], [42, 60], [43, 60], [44, 60], [42, 61], [43, 61], [44, 61], [42, 62], [43, 62], [44, 62]] 
n_ckpt: 250
N_cutoff: -1
w_combine: False    # The method for combining weights. Choices include "None" [unspecified], exp_avg, ...
runtime_args: {'-ntomp': '1'}
grompp_args: {'-maxwarn': '2'}
gro: ['A-B.gro', 'B-C.gro', 'C-D.gro', 'D-E.gro', 'E-F.gro', 'A-D.gro', 'D-F.gro'] 
top: ['A-B.top', 'B-C.top', 'C-D.top', 'D-E.top', 'E-F.top', 'A-D.top', 'D-F.top'] 
gmx_executable: 'gmx'
verbose: True
modify_coords: 'default'
resname_list: ['A2B', 'B2C', 'C2D', 'D2E', 'E2F', 'A2D', 'D2F']
swap_rep_pattern: [[[0,1],[1,0]], [[1,1],[2,0]], [[2,1],[3,0]], [[3,1],[4,0]], [[0,0],[5,0]], [[2,1],[5,1]], [[3,0],[5,1]], [[5,1],[6,0]], [[2,1],[6,0]], [[3,0],[6,0]], [[4,1],[6,1]]]

msm: False
free_energy: True
df_spacing: 1
df_method: "MBAR"
err_method: "propagate"
n_bootstrap: 50
seed : null
